// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get Supabase configuration from environment variables
// These should be set in .env file
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missingVars = [];
  if (!SUPABASE_URL) missingVars.push("VITE_SUPABASE_URL");
  if (!SUPABASE_PUBLISHABLE_KEY) missingVars.push("VITE_SUPABASE_PUBLISHABLE_KEY");
  
  console.error(
    `❌ Missing required Supabase environment variables: ${missingVars.join(", ")}\n` +
    `Please set these in your .env file. See example.env for reference.`
  );
  
  throw new Error(`Missing required environment variables: ${missingVars.join(", ")}`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

import { monitoredFetch } from "@/lib/monitoredFetch";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
        fetch: monitoredFetch,
    },
});
